service: tr-vote
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - 'Fn::GetAtt': [MyDynamoDbTable, Arn]
        - 'Fn::GetAtt': [UserTable, Arn]
functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
plugins:
  - serverless-offline
